appname="求导小助手"
appver="1.7.6"
appcode="23"
packagename="github.znzsofficial.derivate"
theme="Theme_Material_NoActionBar"
welcome_time="0"
debugmode=true
enableExtendedOutputSupport=false
enableDialogLog=false
user_permission={
  "VIBRATE"
}
